---
title: "ESM204 Homework 4 - Social Cost of Carbon"
author: "Nick Bissonnette, Taylor Lockmann, Laurel Wee"
date: "5/22/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```


## 1. Estimate a quadratic function relating damages to temperature

```{r}
damages_data <- read_csv(here("data", "damages.csv")) %>% clean_names()

warming_data <- read_csv(here("data", "warming.csv")) %>% clean_names()

#ggplot(data = damages_data, aes(x = warming, y = damages))+
  #geom_point()+
  #theme_bw()
```

```{r}
#Make the x variable exponential 
damages_data$warming2 <- damages_data$warming^2

quadratic_model <-lm(damages ~ warming + warming2, data = damages_data)

summary(quadratic_model)
```

```{r}
# Name coefficients we got from the above step

a <- quadratic_model$coefficients[[3]]
b <- quadratic_model$coefficients[[2]]

#Write quadratic function using a and b
quadratic_function <- function(x) a*x^2 + b*x

#plot(quadratic_function)

ggplot(data = damages_data, aes(x = warming, y = damages))+
  stat_function(fun = quadratic_function)+
  geom_point()+
  theme_bw()
```

## 2. Damages under baseline climate and pulse

### a) Damages over time without pulse

```{r}
# Use the damages function to create a new column for the warming data set

warming_data$damage_baseline <- quadratic_function(warming_data$warming_baseline)

ggplot(data = warming_data, aes(x = year, y = damage_baseline))+
  geom_point()+
  theme_bw()
```

### b) Damages over time with pulse
```{r}
# Use damages function to create a new column for warming data set
warming_data$damage_pulse <- quadratic_function(warming_data$warming_pulse)

ggplot(data = warming_data, aes(x = year, y = damage_pulse))+
  geom_point()+
  theme_bw()
```

### c) Difference in damages over time that arises from the pulse
```{r}
warming_data$damage_difference <-(warming_data$damage_pulse - warming_data$damage_baseline) 

ggplot(data = warming_data, aes(x = year, y = damage_difference))+
  geom_point()+
  theme_bw()
```

### d) difference in damages over time per ton of CO2

```{r}
warming_data$damage_diff_per_ton <-(warming_data$damage_difference/ 3.5e+10) 

ggplot(data = warming_data, aes(x = year, y = damage_diff_per_ton))+
  geom_point()+
  theme_bw()
```

## 3. Social Cost of Carbon 

```{r}
# Write a function for the social cost of carbon (SCC) according to discount rate
scc <- function(r) warming_data$damage_diff_per_ton/((1+r)^warming_data$x1)

# Make new columns of different discount rates
warming_data$scc_1 <- scc(0.01)
warming_data$scc_2 <- scc(0.02)
warming_data$scc_3 <- scc(0.03)
warming_data$scc_4 <- scc(0.04)
warming_data$scc_5 <- scc(0.05)
```

```{r}
scc_1_sum <- sum(warming_data$scc_1)

scc_2_sum <- sum(warming_data$scc_2)

scc_3_sum <- sum(warming_data$scc_3)

scc_4_sum <- sum(warming_data$scc_4)

scc_5_sum <- sum(warming_data$scc_5)

#make vectors
damage_per_ton <- c(scc_1_sum,scc_2_sum, scc_3_sum, scc_4_sum, scc_5_sum )

r <- c(0.01, 0.02, 0.03, 0.04, 0.05)
scc_df<- data.frame(r,damage_per_ton)

ggplot(data= scc_df, aes(x= r, y=damage_per_ton)) +
  geom_point()+
  geom_line()+
  theme_bw()

```


## 4. Ramsey Rule SCC calculation

```{r}
# Function for Ramsey Rule
ramsey_rule <- function(p, n, g) p + n*g

# Find the SCC for our given values
ramsey_rule(p = 0.001, n = 2, g = 0.01)
```
```{r}
# Make new column in our warming data of this discount rate
warming_data$scc_2.1 <- scc(0.021)
# Find the sum of damages at this SCC
scc_2.1_sum <- sum(warming_data$scc_2.1)

#make vectors
ramsey_damage_per_ton <- c(scc_1_sum,scc_2_sum, scc_2.1_sum, scc_3_sum, scc_4_sum, scc_5_sum )

ramsey_r <- c(0.01, 0.02, 0.021, 0.03, 0.04, 0.05)
ramsey_scc_df<- data.frame(ramsey_r,ramsey_damage_per_ton)

# Plot this point on our graph from 4d
ggplot(data= ramsey_scc_df, aes(x= ramsey_r, y=ramsey_damage_per_ton)) +
  geom_point()+
  geom_line()+
  theme_bw()
  
```




## 5. 
```{r}
#Find the present value of damages 
warming_data$base_a <- warming_data$damage_baseline/((1+.02)^warming_data$x1)

present_val_base_a_sum <- sum(warming_data$base_a)

# add 1.5 degrees to warming values and rerun 
```

